name: Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "cpp, rust"

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Run SonarQube Analysis
        run: sonar-scanner
