name: Database Backup

on:
  schedule:
    - cron: "0 2 * * *" # Run daily at 2 AM

jobs:
  backup-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Backup Database
        run: |
          PGPASSWORD=${{ secrets.DB_PASSWORD }} pg_dump -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} ${{ secrets.DB_NAME }} > backup.sql

      - name: Upload Backup to Storage
        uses: actions/upload-artifact@v3
        with:
          name: database-backup
          path: backup.sql
